# -*- coding: utf-8 -*-
"""CDS_HW3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19dakuWLtPiyes8dd9EjNvbdMhMBtmYdI
"""

phone_number={}

command_list=['a','d','f','q','s']



#print(command)

allowed_chars = ("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.'- ")

not_legal=True

repeat_command=True


while repeat_command:
  command=input("Enter a one-letter command [adfqs]: ")
  if command in command_list:

    #print("item in command list")
    if(command=="a"):
      print("Add a person's name and associated phone number.")
      not_legal=True
      while not_legal:
          name=input("Enter the person's name: ")
          for char in name:
            if ((char not in allowed_chars) or (len(allowed_chars)<1)):
              print("Letter '"+char+"' is not legal in a name; try again.")
              not_legal=True
              break
            else:
              not_legal=False

      if(not_legal==False):
        all_digits=True
        while True:
          number=input("Enter the person's phone number (10 digits): ")
          for char in number:
            if not char.isdigit():
              all_digits=False
              print("Phone number must have exactly 10 digits; try again.")
              break
            else:
              all_digits=True

          if((len(number)!=10) & (all_digits==True)):
            print("Phone number must have exactly 10 digits; try again." )
           # print(len(number))
          elif((len(number)==10) & (all_digits==True)):
            phone_number[name]=number
            #print(phone_number[name]
            break


    elif (command=='q'):
      repeat_command=False

    elif(command=='s'):
      print("Show all the items in the database.")
      for key in phone_number:
        print(key +" has phone number "+ phone_number[key])

    elif(command=='f'):

      zero_entry=True
      print("Find database entries by substring of a person's name.")
      substring=input("Enter the substring to search for: ")
      for key in phone_number:
        if substring in key:
          print("Found ("+key+","+phone_number[key]+")" )
          zero_entry=False
      if(zero_entry==True):
        print("Zero entries found!")



    elif(command=='d'):
      print("Delete a person's name.")
      name=input("Enter the person's name: ")
      if name not in phone_number:
        print("Name '"+name+"' not in the database, not deleted")
      else:

        print("Successfully deleted ("+name+","+phone_number[name]+")")
        del phone_number[name]



  else:
    print("Invalid command; try again.")